### ISSUE TITLE
graphql connection refused

### ISSUE THREAD

**Issue by Khobalt** [IgorMCesar/react-express-mongo-boilerplate#38]
First of all, thanks for putting this together.
I'm new to this stack and there's so many rabbit holes to go down, but this repo is exactly what I wanted. 
Anyway, I've installed everything and I'm trying to run the example, but I'm running into this error.
![image](https://user-images.githubusercontent.com/848683/65293420-13396900-db10-11e9-92de-e6406f177b59.png)

Screenshot above for the human eye, 
copied below for googling purposes...

Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./node_modules/zen-observable/lib/Observable.js?:63 Uncaught TypeError: Cannot read property 'map' of undefined
    at onError (webpack:///./config/createApolloClient.js?:13)
    at Object.error (webpack:///./node_modules/apollo-link-error/lib/bundle.esm.js?:37)
    at notifySubscription (webpack:///./node_modules/zen-observable/lib/Observable.js?:134)
    at onNotify (webpack:///./node_modules/zen-observable/lib/Observable.js?:165)
    at SubscriptionObserver.error (webpack:///./node_modules/zen-observable/lib/Observable.js?:224)
    at eval (webpack:///./node_modules/apollo-link-http/lib/bundle.esm.js?:92)
onError @ webpack:///./config/createApolloClient.js?:13
error @ webpack:///./node_modules/apollo-link-error/lib/bundle.esm.js?:37
notifySubscription @ webpack:///./node_modules/zen-observable/lib/Observable.js?:134
onNotify @ webpack:///./node_modules/zen-observable/lib/Observable.js?:165
error @ webpack:///./node_modules/zen-observable/lib/Observable.js?:224
(anonymous) @ webpack:///./node_modules/apollo-link-http/lib/bundle.esm.js?:92
webpack:///(webpack)-dev-server/client?:52 [WDS] Live Reloading enabled.

**Comment by IgorMCesar** [comment]
First of all, I am really glad to know this project may help you learn something new! =)

About your problem:
You are probably using "master" branch, and i didn't fix ```createApolloClient.js``` basic error handling yet. So what you are experiencing is a mix of two problems. The first one is that for some reason your server instance is not up or is rejecting the client request. The second one is happening because the server connection is not going through, so ```graphQLErrors``` doesn't exist and an error will occur as we are trying to map an undefined variable. 

What i can suggest is:

1- Try using ```refactor/hooks``` branch for now.
2- Make sure your server instance is running. Check if this url works http://localhost:8080/graphql

**Comment by Khobalt** [comment]
I wasn't even running the server. Derp.
I thought npm run dev would fire everything up from the root, but I was mistaken.
Thanks again!

**Comment by IgorMCesar** [comment]
It actually should start everything, you sure it didn't? Wasn't it just an error?

**Comment by Khobalt** [comment]
Yeah, all that happened was the client spun up with a spinning wheel in the UI.
When I ran npm run dev in both the client and server folders everything worked.

**Comment by Khobalt** [comment]
I don't know what was going on, I've done a fresh install of this a few more times and it works just fine.
